version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearch_compose
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - network.host= 0.0.0.0
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    networks:
      - es-net
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: 2g
    

  kibana:
    container_name: kibana_compose
    image: docker.elastic.co/kibana/kibana:8.5.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    mem_limit: 2g


  logstash:
    container_name: logstash_compose
    image: docker.elastic.co/logstash/logstash:8.6.1
    command: bash -c "cd bin && logstash-plugin install logstash-input-mongodb && logstash -f /etc/logstash/conf.d/mongodb_input.conf"
    volumes:
      - ./:/etc/logstash/conf.d # folder config logstash input from mongo to elasticsearch
      - ./logstash-mongodb:/opt/logstash-mongodb/
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - es-net
    mem_limit: 2g


networks:
  es-net:
    driver: bridge
